//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClientGlpi.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.5.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://192.168.16.12:81/apirest.php")]
        public string GLPI_URL0 {
            get {
                return ((string)(this["GLPI_URL0"]));
            }
            set {
                this["GLPI_URL0"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("wuy7FLHQZGpgpzDMqP2H8EXsE3pcmYe9PWDoYZPq")]
        public string GLPI_APP_TOKEN0 {
            get {
                return ((string)(this["GLPI_APP_TOKEN0"]));
            }
            set {
                this["GLPI_APP_TOKEN0"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("root")]
        public string GLPI_USER {
            get {
                return ((string)(this["GLPI_USER"]));
            }
            set {
                this["GLPI_USER"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Aa8612310688+9")]
        public string GLPI_PASS {
            get {
                return ((string)(this["GLPI_PASS"]));
            }
            set {
                this["GLPI_PASS"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("BsWfvJcGLxiDqs1YbyWEW6scOxJykmJv87tzIMSh")]
        public string GLPI_APP_TOKEN {
            get {
                return ((string)(this["GLPI_APP_TOKEN"]));
            }
            set {
                this["GLPI_APP_TOKEN"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("rngi")]
        public string GLPI_AUTH {
            get {
                return ((string)(this["GLPI_AUTH"]));
            }
            set {
                this["GLPI_AUTH"] = value;
            }
        }
    }
}
